#Configuração de rotas
/portal:  PaginaLoginController
/portalAdm: PortalAdmController
/cadastro: CadastroController

/login-form:  LoginFormController
/login: LoginController
/logout:  LogoutController

/listar-produtos: ListarProdutosController


/adicionar-estadia-form: AdicionarEstadiaFormController

/apagar-produto:  ApagarProdutoController


/aprovar-pacote: AprovarPacoteController
/reprovar-pacote: ReprovarPacoteController
/cancelar-pacote: CancelarPacoteController

/editar-produto-form: EditarProdutoFormController

/detalhar-pacote: ListarDetalhesPacoteController

/404found:  path404Controller

/cadastro-cliente: CadastroClienteController
